# vim ft=yaml
# travis-ci.org definition

branches:
  only:
    - natsys/trunk

# non-container builds don't have enough RAM to reliably compile
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
#  - clang # See commit f38808 if you want to re-enable clang builds
cache:
  apt:
  ccache:

# Timing on build an test needs to be < 50 minutes. The compile is ~4-5minutes
# so here we group the tests such that this happens.

addons:
  apt:
    packages: # make sure these match debian/control contents
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev # no effect as the package is disallowed on Travis-CI
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu

script:
  - ${CC} --version ; ${CXX} --version
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_INNOBASE_STORAGE_ENGINE=yes -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=no -DWITH_PIC=no -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" -DCMAKE_C_FLAGS_DEBUG="-g -O0"
  - make -j $(grep -c processor /proc/cpuinfo)
  - cd ./mysql-test
  - ./mtr --suite=versioning --force --max-test-fail=0
